"""empty message

Revision ID: 35227a6a2dd1
Revises: 48bf7821c5b3
Create Date: 2025-05-08 15:37:04.682526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35227a6a2dd1'
down_revision = '48bf7821c5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('usersFav_id', sa.Integer(), nullable=False),
    sa.Column('vehiclesFav_id', sa.Integer(), nullable=False),
    sa.Column('planetsFav_id', sa.Integer(), nullable=False),
    sa.Column('charactersFav_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['charactersFav_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planetsFav_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['usersFav_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehiclesFav_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('usersFav_id', 'vehiclesFav_id', 'planetsFav_id', 'charactersFav_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites')
    # ### end Alembic commands ###
